name: ichiban_auto
description: "A tool for managing your car service"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  awesome_snackbar_content: ^0.1.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  syncfusion_flutter_calendar: ^27.1.53
  intl: ^0.19.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/

